// <auto-generated />
using System;
using Contact_Manager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Contact_Manager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240420102306_SeedEmployeeTable")]
    partial class SeedEmployeeTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Contact_Manager.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Married")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1881, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Married = false,
                            Name = "Albus Dumbledore",
                            Phone = "0101221232",
                            Salary = 10000m
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1960, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Married = false,
                            Name = "Severus Snape",
                            Phone = "0104324323",
                            Salary = 7050m
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1890, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Married = true,
                            Name = "Minerva McGonagall",
                            Phone = "0105676567",
                            Salary = 7070m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
